name: oyinshyq
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Show errors
  fluttertoast: ^8.0.8
  # onboarding
  introduction_screen: ^2.1.0
  # Animated progress indicator
  flutter_spinkit: ^5.1.0
  line_icons: ^2.0.1
  google_nav_bar: ^5.0.5
  flutter_multi_formatter: ^2.4.1
  # sms code input
  pinput: ^1.2.0
  dio: ^4.0.0
  # local storage
  shared_preferences: ^2.0.6
  #freezed
  freezed_annotation: ^0.14.1
  #internet connection
  connectivity_plus: ^1.1.0
  # search bar
  anim_search_bar: ^2.0.2


dev_dependencies:
  build_runner:
  freezed: ^0.14.1+1
  flutter_test:
    sdk: flutter
  # Provider state management
  provider: ^6.0.1
  

 

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/icons/svg/
    - assets/icons/png/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
   
        